#!/bin/bash
echo "---"
echo "quickupdate"
echo "by github/aleksiaksu"
echo "License: CC0"
echo "---"
echo "Searching apt..."
if command -v apt &> /dev/null
then
echo "Updating using apt..."
sudo bash -c "apt update && apt -y upgrade"
else
echo "apt not found, skipped..."
fi
echo "---"
echo "Searching flatpak..."
if command -v flatpak &> /dev/null
then
echo "Updating using flatpak..."
sudo bash -c "flatpak update -y"
else
echo "flatpak not found, skipped..."
fi
echo "---"
echo "Searching snap..."
if command -v snap &> /dev/null
then
echo "Updating using snap..."
sudo bash -c "snap refresh"
else
echo "snap not found, skipped..."
fi
echo "---"
